### ISSUE TITLE
FR - progress bar for `salto fetch`

### ISSUE THREAD

**Issue by idanblich** [salto-io/salto#1091]
`salto fetch` is taking a long time ⏳
A progress bar 💈 will be a great for the user to understand that the process is still running

**Comment by eladmallel** [comment]
@idanblich you're right :)

We have plans to add a spinner. The main reason this hasn't happened so far is that it requires a decent amount of refactoring of our CLI, and in the near future we're focusing our efforts on other fronts, like better support for Salesforce, NetSuite and a few other fronts.

Thanks for the feedback, please keep sharing your thoughts! And we'll update you once we improve this part of our UX.

**Comment by ori-moisis** [comment]
Sorry for not updating this issue for a while, but several improvements have been made on this front since this issue was opened and the CLI now shows more detailed progress information.
