### ISSUE TITLE
Improve documentation about running the CLI on Windows

### ISSUE THREAD

**Issue by oliversahr** [salto-io/salto#3178]
Hi,
in the docs/user_guide.md file it says:
"In case you're using some other shell on Windows, please make sure to make the required adjustments."
What are the required adjustments?
I tried it twice on Windows PowerShell, the program did not work. What adjustments are needed on Windows?

Best,
Oliver

**Comment by ori-moisis** [comment]
Hi Oliver

The "required adjustments" mentioned refer to the commands given in the guide, specifically the download instructions use commands that are not generally available in windows shell (e.g `curl`).

There should be no need to adjust anything on your computer for Salto to run on it.

Do note that in a few recent releases we had an issue specifically with windows, so if you tried running a version before [v0.3.19](https://github.com/salto-io/salto/releases/tag/v0.3.19) that may be the reason for the program not working as expected and I suggest you try again with the latest release.

if that does not work, could you please share a few specifics about what is not working?
- which version are you running
- what command are you running
- what was the error message

Thanks

**Comment by oliversahr** [comment]
Hi,
I really should have screenshotted the error message. It was something along the lines of "path invalid". We tried to download from a Zendesk environment. I'll test later on linux if the tool works there or if the error occurs again. If not, I'll try again on windows and post the exact message here. We used the most recent version listed in the Releases, I think.

Best,
Oliver

**Comment by oliversahr** [comment]
Hi,
the error happened on Linux as well, I'll create a separate issue for that.
For this issue I think to add some clarification to above mentioned part in the documentation, like "Install tools like curl on Windows".

Thanks and best regards,
Oliver

**Comment by ori-moisis** [comment]
sounds like it isn't a linux or windows issue.
this might be an issue with fetching you specific account

might be better to discuss this [on slack](https://invite.playplay.io/invite?team_id=T011W61EVHD) instead of opening a bunch of tickets here that may end up being not relevant
